baseURL = 'https://coopyey.gay/'
languageCode = 'en-us'
title = 'coops corner'
theme = "cyberscape"

# Enable this for tailwind in markdown files
[markup.goldmark.renderer]
unsafe=true

# Add menu links to things from /content/ here (eg. markdown.md)
[[menu.main]]
    name = "ttrpg"
    pageRef = "ttrpg"
    url = "/ttrpg-campaigns/"
    weight = 20

[[menu.main]]
    name = "artists"
    pageRef = "artists"
    url = "/artists/"
    weight = 10

[[menu.main]]
    name = "paper"
    pageRef = "paper"
    url = "/papercraft/"
    weight = 30

[[menu.main]]
    name = "journals"
    pageRef = "journals"
    url = "/journaling/"
    weight = 40